### ISSUE TITLE
rubocop errors

### ISSUE THREAD

**Issue by dwbenjamin** [yast/yast-devtools#153]
Using yast2-devtools-4.1.2-lp151.1.1.noarch
/usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

`rake check:rubocop`
Error: obsolete parameter
`IndentWhenRelativeTo` has been renamed to `EnforcedStyle`
`AlignWith` has been renamed to `EnforcedStyleAlignWith`

**Comment by ancorgs** [comment]
First of all, sorry for the delay in replying. 

The fact is that the list of settings supported by Rubocop changes quite a lot from one version to another. 

So, to make sure the configuration provided by a certain version of yast2-devtools works, you should use the version of rubocop available in the corresponding YaST repository (which may match or not the version currently available in the distribution).

Example:

 - For Tumbleweed https://build.opensuse.org/package/show/YaST:Head/rubygem-rubocop
 - For 15.1 https://build.opensuse.org/package/show/YaST:SLE-15:SP1/rubygem-rubocop

Sorry for the inconvenience.
